First xUnit testing - disappointment
I spent the whole day trying to make xUnit work. I'll come back to it eventually, but the project doesn't run at all, because of error CS0579 (whether I "dotnet run" or "dotnet test Schefflera.Tests").
And the Test project itself throws an error CS0122, despite said class being public (which doesn't make sense, considering the class is unrestricted).
At least I wrote my first test that I have no way of testing.